### ISSUE TITLE
Thanks! This is the only one Micropython framework I found on Internet

### ISSUE THREAD

**Issue by SeanLyn** [jtobinart/MicroPython_CYD_ESP32-2432S028R#1]
Great job! I just fired your CYD class and it works as expected.
The only change I had to do so far is to update the width and height in ili9341.py.
In[ rdagger's deposit](https://github.com/rdagger/micropython-ili9341), it's `width=240, height=320` and it should be changed to `width=320, height=240`

**Comment by jtobinart** [comment]
Thank you for your input. I tested your suggested width and height (320x240), but it doesn't work properly on my CYD, ESP32-2432S028R. I guess that not all of the CYDs are created the same. I have added a way to change the screen dimensions while initializing the cyd class. 

Example: 
cyd = CYD(rgb_pmw=False, speaker_gain=512, display_width=240, display_height=320)
